version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: maandhise-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: maandhise
    volumes:
      - mongodb_data:/data/db
    networks:
      - maandhise-network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: maandhise-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - maandhise-network

volumes:
  mongodb_data:

networks:
  maandhise-network:
    driver: bridge
